/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Mortal Kombat 4)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x00010008u
#define func_00010008 BootEntry  /* alias */
